# -*- coding: utf-8 -*-
"""Desafio DIO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fLHqOGYv4HhmJs36TmOL6imoSqfSZcLz

# 1 - Desafio Classificador de nível de Herói 🎯

## Objetivo

Crie uma variável para armazenar o nome e a quantidade de experiência (XP) de um herói, depois utilize uma estrutura de decisão para apresentar alguma das mensagens abaixo:

Se XP for menor do que 1.000 = Ferro
Se XP for entre 1.001 e 2.000 = Bronze
Se XP for entre 2.001 e 5.000 = Prata
Se XP for entre 5.001 e 7.000 = Ouro
Se XP for entre 7.001 e 8.000 = Platina
Se XP for entre 8.001 e 9.000 = Ascendente
Se XP for entre 9.001 e 10.000= Imortal
Se XP for maior ou igual a 10.001 = Radiante

## Saída

Ao final deve se exibir uma mensagem:
"O Herói de nome **{nome}** está no nível de **{nivel}**"
"""

print("Bem vindo!")
print("--------------------------------")
NomeDeHeroi = input("Digite o nome do herói:")
print("Qual o nível de XP do herói? de 0 a 10000")
NivelXP = int(input("Digite o nível de XP do herói:"))
print("--------------------------------")


if NivelXP <= 1000:
    NivelXP = "Ferro"

elif 1001 == NivelXP >=2000:
    NivelXP = "Bronze"

elif 2001 == NivelXP >= 5000:
    NivelXP = "Prata"

elif  5001 == NivelXP >= 7000:
    NivelXP = "Ouro"

elif 7001 == NivelXP >= 8000:
  NivelXP = "Platina"

elif 8001 == NivelXP >= 9000:
    NivelXP = "Ascendente"

elif 9001 == NivelXP >= 10000:
  NivelXP = "Imortal"

elif NivelXP >= 10000:
    NivelXP = "Radiante"


print("O Herói de nome", NomeDeHeroi, "está no nível de ", NivelXP)

"""#  2 - Calculadora de partidas Rankeadas 🎯

## Objetivo:

Crie uma função que recebe como parâmetro a quantidade de vitórias e derrotas de um jogador,
depois disso retorne o resultado para uma variável, o saldo de Rankeadas deve ser feito através do calculo (vitórias - derrotas)

Se vitórias for menor do que 10 = Ferro
Se vitórias for entre 11 e 20 = Bronze
Se vitórias for entre 21 e 50 = Prata
Se vitórias for entre 51 e 80 = Ouro
Se vitórias for entre 81 e 90 = Diamante
Se vitórias for entre 91 e 100= Lendário
Se vitórias for maior ou igual a 101 = Imortal

## Saída

Ao final deve se exibir uma mensagem:
"O Herói tem de saldo de **{saldoVitorias}** está no nível de **{nivel}**"

"""

print("Bem vindo!")
print("--------------------------------")
vitorias = int(input("Digite o número de vitórias:"))
derrotas = int(input("Digite o número de derrotas:"))
print("--------------------------------")

def saldoVitorias (vitorias, derrotas):
  return vitorias - derrotas

Nivel = saldoVitorias(vitorias, derrotas)

if vitorias < 10:
  vitorias = "Ferro"
elif 11 >= vitorias <= 20:
  vitorias = "Bronze"
elif  21 >= vitorias <=  50:
  vitorias =  "Prata"
elif 51 >= vitorias <= 80:
  vitorias =  "Ouro"
elif  81 >= vitorias <= 90:
  vitorias =  "Diamante"
elif 91 >= vitorias <=  100:
  vitorias =  "Lendário"
elif vitorias >= 101:
  vitorias = "Imortal"

print("O Herói tem de saldo de ", vitorias, " e está no nível ", Nivel)

"""# 3 - Escrevendo as classes de um Jogo 🎯

## Objetivo:

Crie uma classe generica que represente um herói de uma aventura e que possua as seguintes propriedades:

- nome
- idade
- tipo (ex: guerreiro, mago, monge, ninja )

além disso, deve ter um método chamado atacar que deve atender os seguientes requisitos:

- exibir a mensagem: "o {tipo} atacou usando {ataque}")
- aonde o {tipo} deve ser concatenando o tipo que está na propriedade da classe
- e no {ataque} deve seguir uma descrição diferente conforme o tipo, seguindo a tabela abaixo:

se mago -> no ataque exibir (usou magia)
se guerreiro -> no ataque exibir (usou espada)
se monge -> no ataque exibir (usou artes marciais)
se ninja -> no ataque exibir (usou shuriken)

## Saída

Ao final deve se exibir uma mensagem:

- "o {tipo} atacou usando {ataque}"
  ex: mago atacou usando magia
  guerreiro atacou usando espada
"""

print("Bem vindo!")
print("--------------------------------")
nome = input("Digite o nome do herói: ")
idade = int(input("Digite a idade do herói: "))
print("Qual o tipo de herói? guerreiro, mago, monge ou ninja")
tipo = str(input("Digite o tipo do herói:"))
print("--------------------------------")

while(tipo != "guerreiro") and (tipo != "mago") and (tipo  != "monge") and (tipo  != "ninja"):
  print("Tipo de herói incorreto, por favor escolha entre as opções: guerreiro, mago, monge ou ninja")
  tipo = str(input("Digite o tipo do herói:"))

else:
  if   tipo == "guerreiro":
        ataque = "a espada"

  elif tipo == "mago":
      ataque = "magia"

  elif tipo == "monge":
        ataque = "artes marciais"

  elif tipo == "ninja":
        ataque =  "shuriken"


print( "O", tipo, "atacou usando", ataque)